string state_check
int8 robot_id
geometry_msgs/Pose[] motion_primitive_info

---

string state_answer
max_min_lp_msgs/server_to_robots neighbor_info
max_min_lp_msgs/general_node[] gen_r_node
max_min_lp_msgs/general_node[] gen_p_r_node
max_min_lp_msgs/general_node[] gen_p_t_node
max_min_lp_msgs/general_node[] gen_t_node

int8 max_neighbor_hop
int8 num_neighbors_at_each_hop
int8 num_new_targets_at_each_hop

## ROBOT info
# ROBOT to robot
int8[] ROBOT_num_robot
int8[] prev_accumulate_robot
int8 num_survived_robot

# ROBOT to motion primitive
int8[] ROBOT_num_motion_primitive
int8[] prev_accumulate_motion_primitive
int8 num_survived_motion_primitive

float64[] constraint_value